export interface WorldCountry {
  name: string;
  isoCode: string;
  iso3: string;
  phoneCode: string;
  currencyCode: string;
  currencyName: string;
  currencySymbol: string;
  flag: string;
  flagUrl: string;
  imageUrl: string;
}

export interface WorldCurrency {
  code: string;
  name: string;
  symbol: string;
  rateFromEUR: number; // approximate real base exchange rate
  rateFromUSD: number;
}

export const WORLD_COUNTRIES: WorldCountry[] = [
  {
    "name": "India",
    "isoCode": "IN",
    "iso3": "IND",
    "phoneCode": "+91",
    "currencyCode": "INR",
    "currencyName": "Indian Rupee",
    "currencySymbol": "₹",
    "flag": "🇮🇳",
    "flagUrl": "https://flagcdn.com/w80/in.png",
    "imageUrl": "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "United States",
    "isoCode": "US",
    "iso3": "USA",
    "phoneCode": "+1",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇺🇸",
    "flagUrl": "https://flagcdn.com/w80/us.png",
    "imageUrl": "https://images.unsplash.com/photo-1506146332389-18140dc7b2fb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "United Kingdom",
    "isoCode": "GB",
    "iso3": "GBR",
    "phoneCode": "+44",
    "currencyCode": "GBP",
    "currencyName": "British Pound",
    "currencySymbol": "£",
    "flag": "🇬🇧",
    "flagUrl": "https://flagcdn.com/w80/gb.png",
    "imageUrl": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "United Arab Emirates",
    "isoCode": "AE",
    "iso3": "ARE",
    "phoneCode": "+971",
    "currencyCode": "AED",
    "currencyName": "UAE Dirham",
    "currencySymbol": "AED",
    "flag": "🇦🇪",
    "flagUrl": "https://flagcdn.com/w80/ae.png",
    "imageUrl": "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Ireland",
    "isoCode": "IE",
    "iso3": "IRL",
    "phoneCode": "+353",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇮🇪",
    "flagUrl": "https://flagcdn.com/w80/ie.png",
    "imageUrl": "https://images.unsplash.com/photo-1590089415225-401ed6f9db8e?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Spain",
    "isoCode": "ES",
    "iso3": "ESP",
    "phoneCode": "+34",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇪🇸",
    "flagUrl": "https://flagcdn.com/w80/es.png",
    "imageUrl": "https://images.unsplash.com/photo-1543783207-ec64e4d95325?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "France",
    "isoCode": "FR",
    "iso3": "FRA",
    "phoneCode": "+33",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇫🇷",
    "flagUrl": "https://flagcdn.com/w80/fr.png",
    "imageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Germany",
    "isoCode": "DE",
    "iso3": "DEU",
    "phoneCode": "+49",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇩🇪",
    "flagUrl": "https://flagcdn.com/w80/de.png",
    "imageUrl": "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Netherlands",
    "isoCode": "NL",
    "iso3": "NLD",
    "phoneCode": "+31",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇳🇱",
    "flagUrl": "https://flagcdn.com/w80/nl.png",
    "imageUrl": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Italy",
    "isoCode": "IT",
    "iso3": "ITA",
    "phoneCode": "+39",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇮🇹",
    "flagUrl": "https://flagcdn.com/w80/it.png",
    "imageUrl": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Switzerland",
    "isoCode": "CH",
    "iso3": "CHE",
    "phoneCode": "+41",
    "currencyCode": "CHF",
    "currencyName": "Swiss Franc",
    "currencySymbol": "CHF",
    "flag": "🇨🇭",
    "flagUrl": "https://flagcdn.com/w80/ch.png",
    "imageUrl": "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Portugal",
    "isoCode": "PT",
    "iso3": "PRT",
    "phoneCode": "+351",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇵🇹",
    "flagUrl": "https://flagcdn.com/w80/pt.png",
    "imageUrl": "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Canada",
    "isoCode": "CA",
    "iso3": "CAN",
    "phoneCode": "+1",
    "currencyCode": "CAD",
    "currencyName": "Canadian Dollar",
    "currencySymbol": "C$",
    "flag": "🇨🇦",
    "flagUrl": "https://flagcdn.com/w80/ca.png",
    "imageUrl": "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Australia",
    "isoCode": "AU",
    "iso3": "AUS",
    "phoneCode": "+61",
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "A$",
    "flag": "🇦🇺",
    "flagUrl": "https://flagcdn.com/w80/au.png",
    "imageUrl": "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Singapore",
    "isoCode": "SG",
    "iso3": "SGP",
    "phoneCode": "+65",
    "currencyCode": "SGD",
    "currencyName": "Singapore Dollar",
    "currencySymbol": "S$",
    "flag": "🇸🇬",
    "flagUrl": "https://flagcdn.com/w80/sg.png",
    "imageUrl": "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Monaco",
    "isoCode": "MC",
    "iso3": "MCO",
    "phoneCode": "+377",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇲🇨",
    "flagUrl": "https://flagcdn.com/w80/mc.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Japan",
    "isoCode": "JP",
    "iso3": "JPN",
    "phoneCode": "+81",
    "currencyCode": "JPY",
    "currencyName": "Japanese Yen",
    "currencySymbol": "¥",
    "flag": "🇯🇵",
    "flagUrl": "https://flagcdn.com/w80/jp.png",
    "imageUrl": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Austria",
    "isoCode": "AT",
    "iso3": "AUT",
    "phoneCode": "+43",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇦🇹",
    "flagUrl": "https://flagcdn.com/w80/at.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Belgium",
    "isoCode": "BE",
    "iso3": "BEL",
    "phoneCode": "+32",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇧🇪",
    "flagUrl": "https://flagcdn.com/w80/be.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Greece",
    "isoCode": "GR",
    "iso3": "GRC",
    "phoneCode": "+30",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇬🇷",
    "flagUrl": "https://flagcdn.com/w80/gr.png",
    "imageUrl": "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Sweden",
    "isoCode": "SE",
    "iso3": "SWE",
    "phoneCode": "+46",
    "currencyCode": "SEK",
    "currencyName": "Swedish Krona",
    "currencySymbol": "kr",
    "flag": "🇸🇪",
    "flagUrl": "https://flagcdn.com/w80/se.png",
    "imageUrl": "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Norway",
    "isoCode": "NO",
    "iso3": "NOR",
    "phoneCode": "+47",
    "currencyCode": "NOK",
    "currencyName": "Norwegian Krone",
    "currencySymbol": "kr",
    "flag": "🇳🇴",
    "flagUrl": "https://flagcdn.com/w80/no.png",
    "imageUrl": "https://images.unsplash.com/photo-1507272931001-fc06c17e4f43?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Denmark",
    "isoCode": "DK",
    "iso3": "DNK",
    "phoneCode": "+45",
    "currencyCode": "DKK",
    "currencyName": "Danish Krone",
    "currencySymbol": "kr",
    "flag": "🇩🇰",
    "flagUrl": "https://flagcdn.com/w80/dk.png",
    "imageUrl": "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Finland",
    "isoCode": "FI",
    "iso3": "FIN",
    "phoneCode": "+358",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇫🇮",
    "flagUrl": "https://flagcdn.com/w80/fi.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Cyprus",
    "isoCode": "CY",
    "iso3": "CYP",
    "phoneCode": "+357",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇨🇾",
    "flagUrl": "https://flagcdn.com/w80/cy.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Malta",
    "isoCode": "MT",
    "iso3": "MLT",
    "phoneCode": "+356",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇲🇹",
    "flagUrl": "https://flagcdn.com/w80/mt.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Türkiye",
    "isoCode": "TR",
    "iso3": "TUR",
    "phoneCode": "+90",
    "currencyCode": "TRY",
    "currencyName": "Turkish Lira",
    "currencySymbol": "₺",
    "flag": "🇹🇷",
    "flagUrl": "https://flagcdn.com/w80/tr.png",
    "imageUrl": "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Qatar",
    "isoCode": "QA",
    "iso3": "QAT",
    "phoneCode": "+974",
    "currencyCode": "QAR",
    "currencyName": "Qatari Riyal",
    "currencySymbol": "QR",
    "flag": "🇶🇦",
    "flagUrl": "https://flagcdn.com/w80/qa.png",
    "imageUrl": "https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Saudi Arabia",
    "isoCode": "SA",
    "iso3": "SAU",
    "phoneCode": "+966",
    "currencyCode": "SAR",
    "currencyName": "Saudi Riyal",
    "currencySymbol": "﷼",
    "flag": "🇸🇦",
    "flagUrl": "https://flagcdn.com/w80/sa.png",
    "imageUrl": "https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Oman",
    "isoCode": "OM",
    "iso3": "OMN",
    "phoneCode": "+968",
    "currencyCode": "OMR",
    "currencyName": "Omani Rial",
    "currencySymbol": "OMR",
    "flag": "🇴🇲",
    "flagUrl": "https://flagcdn.com/w80/om.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "New Zealand",
    "isoCode": "NZ",
    "iso3": "NZL",
    "phoneCode": "+64",
    "currencyCode": "NZD",
    "currencyName": "New Zealand Dollar",
    "currencySymbol": "NZ$",
    "flag": "🇳🇿",
    "flagUrl": "https://flagcdn.com/w80/nz.png",
    "imageUrl": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "South Africa",
    "isoCode": "ZA",
    "iso3": "ZAF",
    "phoneCode": "+27",
    "currencyCode": "ZAR",
    "currencyName": "South African Rand",
    "currencySymbol": "R",
    "flag": "🇿🇦",
    "flagUrl": "https://flagcdn.com/w80/za.png",
    "imageUrl": "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Brazil",
    "isoCode": "BR",
    "iso3": "BRA",
    "phoneCode": "+55",
    "currencyCode": "BRL",
    "currencyName": "Brazilian Real",
    "currencySymbol": "R$",
    "flag": "🇧🇷",
    "flagUrl": "https://flagcdn.com/w80/br.png",
    "imageUrl": "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Mexico",
    "isoCode": "MX",
    "iso3": "MEX",
    "phoneCode": "+52",
    "currencyCode": "MXN",
    "currencyName": "Mexican Peso",
    "currencySymbol": "Mex$",
    "flag": "🇲🇽",
    "flagUrl": "https://flagcdn.com/w80/mx.png",
    "imageUrl": "https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Thailand",
    "isoCode": "TH",
    "iso3": "THA",
    "phoneCode": "+66",
    "currencyCode": "THB",
    "currencyName": "Thai Baht",
    "currencySymbol": "฿",
    "flag": "🇹🇭",
    "flagUrl": "https://flagcdn.com/w80/th.png",
    "imageUrl": "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Indonesia",
    "isoCode": "ID",
    "iso3": "IDN",
    "phoneCode": "+62",
    "currencyCode": "IDR",
    "currencyName": "Indonesian Rupiah",
    "currencySymbol": "Rp",
    "flag": "🇮🇩",
    "flagUrl": "https://flagcdn.com/w80/id.png",
    "imageUrl": "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Malaysia",
    "isoCode": "MY",
    "iso3": "MYS",
    "phoneCode": "+60",
    "currencyCode": "MYR",
    "currencyName": "Malaysian Ringgit",
    "currencySymbol": "RM",
    "flag": "🇲🇾",
    "flagUrl": "https://flagcdn.com/w80/my.png",
    "imageUrl": "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Philippines",
    "isoCode": "PH",
    "iso3": "PHL",
    "phoneCode": "+63",
    "currencyCode": "PHP",
    "currencyName": "Philippine Peso",
    "currencySymbol": "₱",
    "flag": "🇵🇭",
    "flagUrl": "https://flagcdn.com/w80/ph.png",
    "imageUrl": "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "South Korea",
    "isoCode": "KR",
    "iso3": "KOR",
    "phoneCode": "+82",
    "currencyCode": "KRW",
    "currencyName": "South Korean Won",
    "currencySymbol": "₩",
    "flag": "🇰🇷",
    "flagUrl": "https://flagcdn.com/w80/kr.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Hong Kong",
    "isoCode": "HK",
    "iso3": "HKG",
    "phoneCode": "+852",
    "currencyCode": "HKD",
    "currencyName": "Hong Kong Dollar",
    "currencySymbol": "HK$",
    "flag": "🇭🇰",
    "flagUrl": "https://flagcdn.com/w80/hk.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Afghanistan",
    "isoCode": "AF",
    "iso3": "AFG",
    "phoneCode": "+93",
    "currencyCode": "AFN",
    "currencyName": "AFN Currency",
    "currencySymbol": "AFN",
    "flag": "🇦🇫",
    "flagUrl": "https://flagcdn.com/w80/af.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Aland",
    "isoCode": "AX",
    "iso3": "ALA",
    "phoneCode": "+358",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇦🇽",
    "flagUrl": "https://flagcdn.com/w80/ax.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Albania",
    "isoCode": "AL",
    "iso3": "ALB",
    "phoneCode": "+355",
    "currencyCode": "ALL",
    "currencyName": "ALL Currency",
    "currencySymbol": "ALL",
    "flag": "🇦🇱",
    "flagUrl": "https://flagcdn.com/w80/al.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Algeria",
    "isoCode": "DZ",
    "iso3": "DZA",
    "phoneCode": "+213",
    "currencyCode": "DZD",
    "currencyName": "Algerian Dinar",
    "currencySymbol": "DA",
    "flag": "🇩🇿",
    "flagUrl": "https://flagcdn.com/w80/dz.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "American Samoa",
    "isoCode": "AS",
    "iso3": "ASM",
    "phoneCode": "+1684",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇦🇸",
    "flagUrl": "https://flagcdn.com/w80/as.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Andorra",
    "isoCode": "AD",
    "iso3": "AND",
    "phoneCode": "+376",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇦🇩",
    "flagUrl": "https://flagcdn.com/w80/ad.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Angola",
    "isoCode": "AO",
    "iso3": "AGO",
    "phoneCode": "+244",
    "currencyCode": "AOA",
    "currencyName": "AOA Currency",
    "currencySymbol": "AOA",
    "flag": "🇦🇴",
    "flagUrl": "https://flagcdn.com/w80/ao.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Anguilla",
    "isoCode": "AI",
    "iso3": "AIA",
    "phoneCode": "+1264",
    "currencyCode": "XCD",
    "currencyName": "XCD Currency",
    "currencySymbol": "XCD",
    "flag": "🇦🇮",
    "flagUrl": "https://flagcdn.com/w80/ai.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Antarctica",
    "isoCode": "AQ",
    "iso3": "ATA",
    "phoneCode": "+672",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇦🇶",
    "flagUrl": "https://flagcdn.com/w80/aq.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Antigua and Barbuda",
    "isoCode": "AG",
    "iso3": "ATG",
    "phoneCode": "+1268",
    "currencyCode": "XCD",
    "currencyName": "XCD Currency",
    "currencySymbol": "XCD",
    "flag": "🇦🇬",
    "flagUrl": "https://flagcdn.com/w80/ag.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Argentina",
    "isoCode": "AR",
    "iso3": "ARG",
    "phoneCode": "+54",
    "currencyCode": "ARS",
    "currencyName": "Argentine Peso",
    "currencySymbol": "$",
    "flag": "🇦🇷",
    "flagUrl": "https://flagcdn.com/w80/ar.png",
    "imageUrl": "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Armenia",
    "isoCode": "AM",
    "iso3": "ARM",
    "phoneCode": "+374",
    "currencyCode": "AMD",
    "currencyName": "AMD Currency",
    "currencySymbol": "AMD",
    "flag": "🇦🇲",
    "flagUrl": "https://flagcdn.com/w80/am.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Aruba",
    "isoCode": "AW",
    "iso3": "ABW",
    "phoneCode": "+297",
    "currencyCode": "AWG",
    "currencyName": "AWG Currency",
    "currencySymbol": "AWG",
    "flag": "🇦🇼",
    "flagUrl": "https://flagcdn.com/w80/aw.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Ascension Island",
    "isoCode": "AC",
    "iso3": "ASC",
    "phoneCode": "+247",
    "currencyCode": "SHP",
    "currencyName": "SHP Currency",
    "currencySymbol": "SHP",
    "flag": "🇦🇨",
    "flagUrl": "https://flagcdn.com/w80/ac.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Azerbaijan",
    "isoCode": "AZ",
    "iso3": "AZE",
    "phoneCode": "+994",
    "currencyCode": "AZN",
    "currencyName": "AZN Currency",
    "currencySymbol": "AZN",
    "flag": "🇦🇿",
    "flagUrl": "https://flagcdn.com/w80/az.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Bahamas",
    "isoCode": "BS",
    "iso3": "BHS",
    "phoneCode": "+1242",
    "currencyCode": "BSD",
    "currencyName": "Bahamian Dollar",
    "currencySymbol": "B$",
    "flag": "🇧🇸",
    "flagUrl": "https://flagcdn.com/w80/bs.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Bahrain",
    "isoCode": "BH",
    "iso3": "BHR",
    "phoneCode": "+973",
    "currencyCode": "BHD",
    "currencyName": "Bahraini Dinar",
    "currencySymbol": "BD",
    "flag": "🇧🇭",
    "flagUrl": "https://flagcdn.com/w80/bh.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Bangladesh",
    "isoCode": "BD",
    "iso3": "BGD",
    "phoneCode": "+880",
    "currencyCode": "BDT",
    "currencyName": "Bangladeshi Taka",
    "currencySymbol": "৳",
    "flag": "🇧🇩",
    "flagUrl": "https://flagcdn.com/w80/bd.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Barbados",
    "isoCode": "BB",
    "iso3": "BRB",
    "phoneCode": "+1246",
    "currencyCode": "BBD",
    "currencyName": "Barbadian Dollar",
    "currencySymbol": "Bds$",
    "flag": "🇧🇧",
    "flagUrl": "https://flagcdn.com/w80/bb.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Belarus",
    "isoCode": "BY",
    "iso3": "BLR",
    "phoneCode": "+375",
    "currencyCode": "BYN",
    "currencyName": "BYN Currency",
    "currencySymbol": "BYN",
    "flag": "🇧🇾",
    "flagUrl": "https://flagcdn.com/w80/by.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Belize",
    "isoCode": "BZ",
    "iso3": "BLZ",
    "phoneCode": "+501",
    "currencyCode": "BZD",
    "currencyName": "BZD Currency",
    "currencySymbol": "BZD",
    "flag": "🇧🇿",
    "flagUrl": "https://flagcdn.com/w80/bz.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Benin",
    "isoCode": "BJ",
    "iso3": "BEN",
    "phoneCode": "+229",
    "currencyCode": "XOF",
    "currencyName": "XOF Currency",
    "currencySymbol": "XOF",
    "flag": "🇧🇯",
    "flagUrl": "https://flagcdn.com/w80/bj.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Bermuda",
    "isoCode": "BM",
    "iso3": "BMU",
    "phoneCode": "+1441",
    "currencyCode": "BMD",
    "currencyName": "BMD Currency",
    "currencySymbol": "BMD",
    "flag": "🇧🇲",
    "flagUrl": "https://flagcdn.com/w80/bm.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Bhutan",
    "isoCode": "BT",
    "iso3": "BTN",
    "phoneCode": "+975",
    "currencyCode": "BTN",
    "currencyName": "BTN Currency",
    "currencySymbol": "BTN",
    "flag": "🇧🇹",
    "flagUrl": "https://flagcdn.com/w80/bt.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Bolivia",
    "isoCode": "BO",
    "iso3": "BOL",
    "phoneCode": "+591",
    "currencyCode": "BOB",
    "currencyName": "BOB Currency",
    "currencySymbol": "BOB",
    "flag": "🇧🇴",
    "flagUrl": "https://flagcdn.com/w80/bo.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Bonaire",
    "isoCode": "BQ",
    "iso3": "BES",
    "phoneCode": "+5997",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇧🇶",
    "flagUrl": "https://flagcdn.com/w80/bq.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Bosnia and Herzegovina",
    "isoCode": "BA",
    "iso3": "BIH",
    "phoneCode": "+387",
    "currencyCode": "BAM",
    "currencyName": "BAM Currency",
    "currencySymbol": "BAM",
    "flag": "🇧🇦",
    "flagUrl": "https://flagcdn.com/w80/ba.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Botswana",
    "isoCode": "BW",
    "iso3": "BWA",
    "phoneCode": "+267",
    "currencyCode": "BWP",
    "currencyName": "Botswana Pula",
    "currencySymbol": "P",
    "flag": "🇧🇼",
    "flagUrl": "https://flagcdn.com/w80/bw.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Bouvet Island",
    "isoCode": "BV",
    "iso3": "BVT",
    "phoneCode": "+47",
    "currencyCode": "NOK",
    "currencyName": "Norwegian Krone",
    "currencySymbol": "kr",
    "flag": "🇧🇻",
    "flagUrl": "https://flagcdn.com/w80/bv.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "British Indian Ocean Territory",
    "isoCode": "IO",
    "iso3": "IOT",
    "phoneCode": "+246",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇮🇴",
    "flagUrl": "https://flagcdn.com/w80/io.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "British Virgin Islands",
    "isoCode": "VG",
    "iso3": "VGB",
    "phoneCode": "+1284",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇻🇬",
    "flagUrl": "https://flagcdn.com/w80/vg.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Brunei",
    "isoCode": "BN",
    "iso3": "BRN",
    "phoneCode": "+673",
    "currencyCode": "BND",
    "currencyName": "BND Currency",
    "currencySymbol": "BND",
    "flag": "🇧🇳",
    "flagUrl": "https://flagcdn.com/w80/bn.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Bulgaria",
    "isoCode": "BG",
    "iso3": "BGR",
    "phoneCode": "+359",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇧🇬",
    "flagUrl": "https://flagcdn.com/w80/bg.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Burkina Faso",
    "isoCode": "BF",
    "iso3": "BFA",
    "phoneCode": "+226",
    "currencyCode": "XOF",
    "currencyName": "XOF Currency",
    "currencySymbol": "XOF",
    "flag": "🇧🇫",
    "flagUrl": "https://flagcdn.com/w80/bf.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Burundi",
    "isoCode": "BI",
    "iso3": "BDI",
    "phoneCode": "+257",
    "currencyCode": "BIF",
    "currencyName": "BIF Currency",
    "currencySymbol": "BIF",
    "flag": "🇧🇮",
    "flagUrl": "https://flagcdn.com/w80/bi.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Cabo Verde",
    "isoCode": "CV",
    "iso3": "CPV",
    "phoneCode": "+238",
    "currencyCode": "CVE",
    "currencyName": "CVE Currency",
    "currencySymbol": "CVE",
    "flag": "🇨🇻",
    "flagUrl": "https://flagcdn.com/w80/cv.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Cambodia",
    "isoCode": "KH",
    "iso3": "KHM",
    "phoneCode": "+855",
    "currencyCode": "KHR",
    "currencyName": "KHR Currency",
    "currencySymbol": "KHR",
    "flag": "🇰🇭",
    "flagUrl": "https://flagcdn.com/w80/kh.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Cameroon",
    "isoCode": "CM",
    "iso3": "CMR",
    "phoneCode": "+237",
    "currencyCode": "XAF",
    "currencyName": "XAF Currency",
    "currencySymbol": "XAF",
    "flag": "🇨🇲",
    "flagUrl": "https://flagcdn.com/w80/cm.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Cayman Islands",
    "isoCode": "KY",
    "iso3": "CYM",
    "phoneCode": "+1345",
    "currencyCode": "KYD",
    "currencyName": "KYD Currency",
    "currencySymbol": "KYD",
    "flag": "🇰🇾",
    "flagUrl": "https://flagcdn.com/w80/ky.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Central African Republic",
    "isoCode": "CF",
    "iso3": "CAF",
    "phoneCode": "+236",
    "currencyCode": "XAF",
    "currencyName": "XAF Currency",
    "currencySymbol": "XAF",
    "flag": "🇨🇫",
    "flagUrl": "https://flagcdn.com/w80/cf.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Chad",
    "isoCode": "TD",
    "iso3": "TCD",
    "phoneCode": "+235",
    "currencyCode": "XAF",
    "currencyName": "XAF Currency",
    "currencySymbol": "XAF",
    "flag": "🇹🇩",
    "flagUrl": "https://flagcdn.com/w80/td.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Chile",
    "isoCode": "CL",
    "iso3": "CHL",
    "phoneCode": "+56",
    "currencyCode": "CLP",
    "currencyName": "Chilean Peso",
    "currencySymbol": "$",
    "flag": "🇨🇱",
    "flagUrl": "https://flagcdn.com/w80/cl.png",
    "imageUrl": "https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "China",
    "isoCode": "CN",
    "iso3": "CHN",
    "phoneCode": "+86",
    "currencyCode": "CNY",
    "currencyName": "Chinese Yuan",
    "currencySymbol": "¥",
    "flag": "🇨🇳",
    "flagUrl": "https://flagcdn.com/w80/cn.png",
    "imageUrl": "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Christmas Island",
    "isoCode": "CX",
    "iso3": "CXR",
    "phoneCode": "+61",
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "A$",
    "flag": "🇨🇽",
    "flagUrl": "https://flagcdn.com/w80/cx.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Cocos (Keeling) Islands",
    "isoCode": "CC",
    "iso3": "CCK",
    "phoneCode": "+61",
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "A$",
    "flag": "🇨🇨",
    "flagUrl": "https://flagcdn.com/w80/cc.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Colombia",
    "isoCode": "CO",
    "iso3": "COL",
    "phoneCode": "+57",
    "currencyCode": "COP",
    "currencyName": "Colombian Peso",
    "currencySymbol": "$",
    "flag": "🇨🇴",
    "flagUrl": "https://flagcdn.com/w80/co.png",
    "imageUrl": "https://images.unsplash.com/photo-1583531352515-8884af319dc1?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Comoros",
    "isoCode": "KM",
    "iso3": "COM",
    "phoneCode": "+269",
    "currencyCode": "KMF",
    "currencyName": "KMF Currency",
    "currencySymbol": "KMF",
    "flag": "🇰🇲",
    "flagUrl": "https://flagcdn.com/w80/km.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Cook Islands",
    "isoCode": "CK",
    "iso3": "COK",
    "phoneCode": "+682",
    "currencyCode": "NZD",
    "currencyName": "New Zealand Dollar",
    "currencySymbol": "NZ$",
    "flag": "🇨🇰",
    "flagUrl": "https://flagcdn.com/w80/ck.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Costa Rica",
    "isoCode": "CR",
    "iso3": "CRI",
    "phoneCode": "+506",
    "currencyCode": "CRC",
    "currencyName": "Costa Rican Colon",
    "currencySymbol": "₡",
    "flag": "🇨🇷",
    "flagUrl": "https://flagcdn.com/w80/cr.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Croatia",
    "isoCode": "HR",
    "iso3": "HRV",
    "phoneCode": "+385",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇭🇷",
    "flagUrl": "https://flagcdn.com/w80/hr.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Cuba",
    "isoCode": "CU",
    "iso3": "CUB",
    "phoneCode": "+53",
    "currencyCode": "CUP",
    "currencyName": "CUP Currency",
    "currencySymbol": "CUP",
    "flag": "🇨🇺",
    "flagUrl": "https://flagcdn.com/w80/cu.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Curacao",
    "isoCode": "CW",
    "iso3": "CUW",
    "phoneCode": "+5999",
    "currencyCode": "XCG",
    "currencyName": "XCG Currency",
    "currencySymbol": "XCG",
    "flag": "🇨🇼",
    "flagUrl": "https://flagcdn.com/w80/cw.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Czechia",
    "isoCode": "CZ",
    "iso3": "CZE",
    "phoneCode": "+420",
    "currencyCode": "CZK",
    "currencyName": "Czech Koruna",
    "currencySymbol": "Kč",
    "flag": "🇨🇿",
    "flagUrl": "https://flagcdn.com/w80/cz.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Democratic Republic of the Congo",
    "isoCode": "CD",
    "iso3": "COD",
    "phoneCode": "+243",
    "currencyCode": "CDF",
    "currencyName": "CDF Currency",
    "currencySymbol": "CDF",
    "flag": "🇨🇩",
    "flagUrl": "https://flagcdn.com/w80/cd.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Djibouti",
    "isoCode": "DJ",
    "iso3": "DJI",
    "phoneCode": "+253",
    "currencyCode": "DJF",
    "currencyName": "DJF Currency",
    "currencySymbol": "DJF",
    "flag": "🇩🇯",
    "flagUrl": "https://flagcdn.com/w80/dj.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Dominica",
    "isoCode": "DM",
    "iso3": "DMA",
    "phoneCode": "+1767",
    "currencyCode": "XCD",
    "currencyName": "XCD Currency",
    "currencySymbol": "XCD",
    "flag": "🇩🇲",
    "flagUrl": "https://flagcdn.com/w80/dm.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Dominican Republic",
    "isoCode": "DO",
    "iso3": "DOM",
    "phoneCode": "+1809",
    "currencyCode": "DOP",
    "currencyName": "Dominican Peso",
    "currencySymbol": "RD$",
    "flag": "🇩🇴",
    "flagUrl": "https://flagcdn.com/w80/do.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "East Timor",
    "isoCode": "TL",
    "iso3": "TLS",
    "phoneCode": "+670",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇹🇱",
    "flagUrl": "https://flagcdn.com/w80/tl.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Ecuador",
    "isoCode": "EC",
    "iso3": "ECU",
    "phoneCode": "+593",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇪🇨",
    "flagUrl": "https://flagcdn.com/w80/ec.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Egypt",
    "isoCode": "EG",
    "iso3": "EGY",
    "phoneCode": "+20",
    "currencyCode": "EGP",
    "currencyName": "Egyptian Pound",
    "currencySymbol": "E£",
    "flag": "🇪🇬",
    "flagUrl": "https://flagcdn.com/w80/eg.png",
    "imageUrl": "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "El Salvador",
    "isoCode": "SV",
    "iso3": "SLV",
    "phoneCode": "+503",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇸🇻",
    "flagUrl": "https://flagcdn.com/w80/sv.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Equatorial Guinea",
    "isoCode": "GQ",
    "iso3": "GNQ",
    "phoneCode": "+240",
    "currencyCode": "XAF",
    "currencyName": "XAF Currency",
    "currencySymbol": "XAF",
    "flag": "🇬🇶",
    "flagUrl": "https://flagcdn.com/w80/gq.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Eritrea",
    "isoCode": "ER",
    "iso3": "ERI",
    "phoneCode": "+291",
    "currencyCode": "ERN",
    "currencyName": "ERN Currency",
    "currencySymbol": "ERN",
    "flag": "🇪🇷",
    "flagUrl": "https://flagcdn.com/w80/er.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Estonia",
    "isoCode": "EE",
    "iso3": "EST",
    "phoneCode": "+372",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇪🇪",
    "flagUrl": "https://flagcdn.com/w80/ee.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Eswatini",
    "isoCode": "SZ",
    "iso3": "SWZ",
    "phoneCode": "+268",
    "currencyCode": "SZL",
    "currencyName": "SZL Currency",
    "currencySymbol": "SZL",
    "flag": "🇸🇿",
    "flagUrl": "https://flagcdn.com/w80/sz.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Ethiopia",
    "isoCode": "ET",
    "iso3": "ETH",
    "phoneCode": "+251",
    "currencyCode": "ETB",
    "currencyName": "ETB Currency",
    "currencySymbol": "ETB",
    "flag": "🇪🇹",
    "flagUrl": "https://flagcdn.com/w80/et.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Falkland Islands",
    "isoCode": "FK",
    "iso3": "FLK",
    "phoneCode": "+500",
    "currencyCode": "FKP",
    "currencyName": "FKP Currency",
    "currencySymbol": "FKP",
    "flag": "🇫🇰",
    "flagUrl": "https://flagcdn.com/w80/fk.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Faroe Islands",
    "isoCode": "FO",
    "iso3": "FRO",
    "phoneCode": "+298",
    "currencyCode": "DKK",
    "currencyName": "Danish Krone",
    "currencySymbol": "kr",
    "flag": "🇫🇴",
    "flagUrl": "https://flagcdn.com/w80/fo.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Fiji",
    "isoCode": "FJ",
    "iso3": "FJI",
    "phoneCode": "+679",
    "currencyCode": "FJD",
    "currencyName": "FJD Currency",
    "currencySymbol": "FJD",
    "flag": "🇫🇯",
    "flagUrl": "https://flagcdn.com/w80/fj.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "French Guiana",
    "isoCode": "GF",
    "iso3": "GUF",
    "phoneCode": "+594",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇬🇫",
    "flagUrl": "https://flagcdn.com/w80/gf.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "French Polynesia",
    "isoCode": "PF",
    "iso3": "PYF",
    "phoneCode": "+689",
    "currencyCode": "XPF",
    "currencyName": "XPF Currency",
    "currencySymbol": "XPF",
    "flag": "🇵🇫",
    "flagUrl": "https://flagcdn.com/w80/pf.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "French Southern Territories",
    "isoCode": "TF",
    "iso3": "ATF",
    "phoneCode": "+262",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇹🇫",
    "flagUrl": "https://flagcdn.com/w80/tf.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Gabon",
    "isoCode": "GA",
    "iso3": "GAB",
    "phoneCode": "+241",
    "currencyCode": "XAF",
    "currencyName": "XAF Currency",
    "currencySymbol": "XAF",
    "flag": "🇬🇦",
    "flagUrl": "https://flagcdn.com/w80/ga.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Gambia",
    "isoCode": "GM",
    "iso3": "GMB",
    "phoneCode": "+220",
    "currencyCode": "GMD",
    "currencyName": "GMD Currency",
    "currencySymbol": "GMD",
    "flag": "🇬🇲",
    "flagUrl": "https://flagcdn.com/w80/gm.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Georgia",
    "isoCode": "GE",
    "iso3": "GEO",
    "phoneCode": "+995",
    "currencyCode": "GEL",
    "currencyName": "GEL Currency",
    "currencySymbol": "GEL",
    "flag": "🇬🇪",
    "flagUrl": "https://flagcdn.com/w80/ge.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Ghana",
    "isoCode": "GH",
    "iso3": "GHA",
    "phoneCode": "+233",
    "currencyCode": "GHS",
    "currencyName": "Ghanaian Cedi",
    "currencySymbol": "GH₵",
    "flag": "🇬🇭",
    "flagUrl": "https://flagcdn.com/w80/gh.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Gibraltar",
    "isoCode": "GI",
    "iso3": "GIB",
    "phoneCode": "+350",
    "currencyCode": "GIP",
    "currencyName": "GIP Currency",
    "currencySymbol": "GIP",
    "flag": "🇬🇮",
    "flagUrl": "https://flagcdn.com/w80/gi.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Greenland",
    "isoCode": "GL",
    "iso3": "GRL",
    "phoneCode": "+299",
    "currencyCode": "DKK",
    "currencyName": "Danish Krone",
    "currencySymbol": "kr",
    "flag": "🇬🇱",
    "flagUrl": "https://flagcdn.com/w80/gl.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Grenada",
    "isoCode": "GD",
    "iso3": "GRD",
    "phoneCode": "+1473",
    "currencyCode": "XCD",
    "currencyName": "XCD Currency",
    "currencySymbol": "XCD",
    "flag": "🇬🇩",
    "flagUrl": "https://flagcdn.com/w80/gd.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Guadeloupe",
    "isoCode": "GP",
    "iso3": "GLP",
    "phoneCode": "+590",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇬🇵",
    "flagUrl": "https://flagcdn.com/w80/gp.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Guam",
    "isoCode": "GU",
    "iso3": "GUM",
    "phoneCode": "+1671",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇬🇺",
    "flagUrl": "https://flagcdn.com/w80/gu.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Guatemala",
    "isoCode": "GT",
    "iso3": "GTM",
    "phoneCode": "+502",
    "currencyCode": "GTQ",
    "currencyName": "GTQ Currency",
    "currencySymbol": "GTQ",
    "flag": "🇬🇹",
    "flagUrl": "https://flagcdn.com/w80/gt.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Guernsey",
    "isoCode": "GG",
    "iso3": "GGY",
    "phoneCode": "+44",
    "currencyCode": "GBP",
    "currencyName": "British Pound",
    "currencySymbol": "£",
    "flag": "🇬🇬",
    "flagUrl": "https://flagcdn.com/w80/gg.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Guinea",
    "isoCode": "GN",
    "iso3": "GIN",
    "phoneCode": "+224",
    "currencyCode": "GNF",
    "currencyName": "GNF Currency",
    "currencySymbol": "GNF",
    "flag": "🇬🇳",
    "flagUrl": "https://flagcdn.com/w80/gn.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Guinea-Bissau",
    "isoCode": "GW",
    "iso3": "GNB",
    "phoneCode": "+245",
    "currencyCode": "XOF",
    "currencyName": "XOF Currency",
    "currencySymbol": "XOF",
    "flag": "🇬🇼",
    "flagUrl": "https://flagcdn.com/w80/gw.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Guyana",
    "isoCode": "GY",
    "iso3": "GUY",
    "phoneCode": "+592",
    "currencyCode": "GYD",
    "currencyName": "GYD Currency",
    "currencySymbol": "GYD",
    "flag": "🇬🇾",
    "flagUrl": "https://flagcdn.com/w80/gy.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Haiti",
    "isoCode": "HT",
    "iso3": "HTI",
    "phoneCode": "+509",
    "currencyCode": "HTG",
    "currencyName": "HTG Currency",
    "currencySymbol": "HTG",
    "flag": "🇭🇹",
    "flagUrl": "https://flagcdn.com/w80/ht.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Heard Island and McDonald Islands",
    "isoCode": "HM",
    "iso3": "HMD",
    "phoneCode": "+61",
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "A$",
    "flag": "🇭🇲",
    "flagUrl": "https://flagcdn.com/w80/hm.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Honduras",
    "isoCode": "HN",
    "iso3": "HND",
    "phoneCode": "+504",
    "currencyCode": "HNL",
    "currencyName": "HNL Currency",
    "currencySymbol": "HNL",
    "flag": "🇭🇳",
    "flagUrl": "https://flagcdn.com/w80/hn.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Hungary",
    "isoCode": "HU",
    "iso3": "HUN",
    "phoneCode": "+36",
    "currencyCode": "HUF",
    "currencyName": "Hungarian Forint",
    "currencySymbol": "Ft",
    "flag": "🇭🇺",
    "flagUrl": "https://flagcdn.com/w80/hu.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Iceland",
    "isoCode": "IS",
    "iso3": "ISL",
    "phoneCode": "+354",
    "currencyCode": "ISK",
    "currencyName": "Icelandic Krona",
    "currencySymbol": "kr",
    "flag": "🇮🇸",
    "flagUrl": "https://flagcdn.com/w80/is.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Iran",
    "isoCode": "IR",
    "iso3": "IRN",
    "phoneCode": "+98",
    "currencyCode": "IRR",
    "currencyName": "IRR Currency",
    "currencySymbol": "IRR",
    "flag": "🇮🇷",
    "flagUrl": "https://flagcdn.com/w80/ir.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Iraq",
    "isoCode": "IQ",
    "iso3": "IRQ",
    "phoneCode": "+964",
    "currencyCode": "IQD",
    "currencyName": "IQD Currency",
    "currencySymbol": "IQD",
    "flag": "🇮🇶",
    "flagUrl": "https://flagcdn.com/w80/iq.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Isle of Man",
    "isoCode": "IM",
    "iso3": "IMN",
    "phoneCode": "+44",
    "currencyCode": "GBP",
    "currencyName": "British Pound",
    "currencySymbol": "£",
    "flag": "🇮🇲",
    "flagUrl": "https://flagcdn.com/w80/im.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Israel",
    "isoCode": "IL",
    "iso3": "ISR",
    "phoneCode": "+972",
    "currencyCode": "ILS",
    "currencyName": "Israeli Shekel",
    "currencySymbol": "₪",
    "flag": "🇮🇱",
    "flagUrl": "https://flagcdn.com/w80/il.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Ivory Coast",
    "isoCode": "CI",
    "iso3": "CIV",
    "phoneCode": "+225",
    "currencyCode": "XOF",
    "currencyName": "XOF Currency",
    "currencySymbol": "XOF",
    "flag": "🇨🇮",
    "flagUrl": "https://flagcdn.com/w80/ci.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Jamaica",
    "isoCode": "JM",
    "iso3": "JAM",
    "phoneCode": "+1876",
    "currencyCode": "JMD",
    "currencyName": "Jamaican Dollar",
    "currencySymbol": "J$",
    "flag": "🇯🇲",
    "flagUrl": "https://flagcdn.com/w80/jm.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Jersey",
    "isoCode": "JE",
    "iso3": "JEY",
    "phoneCode": "+44",
    "currencyCode": "GBP",
    "currencyName": "British Pound",
    "currencySymbol": "£",
    "flag": "🇯🇪",
    "flagUrl": "https://flagcdn.com/w80/je.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Jordan",
    "isoCode": "JO",
    "iso3": "JOR",
    "phoneCode": "+962",
    "currencyCode": "JOD",
    "currencyName": "Jordanian Dinar",
    "currencySymbol": "JD",
    "flag": "🇯🇴",
    "flagUrl": "https://flagcdn.com/w80/jo.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Kazakhstan",
    "isoCode": "KZ",
    "iso3": "KAZ",
    "phoneCode": "+7",
    "currencyCode": "KZT",
    "currencyName": "KZT Currency",
    "currencySymbol": "KZT",
    "flag": "🇰🇿",
    "flagUrl": "https://flagcdn.com/w80/kz.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Kenya",
    "isoCode": "KE",
    "iso3": "KEN",
    "phoneCode": "+254",
    "currencyCode": "KES",
    "currencyName": "Kenyan Shilling",
    "currencySymbol": "KSh",
    "flag": "🇰🇪",
    "flagUrl": "https://flagcdn.com/w80/ke.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Kiribati",
    "isoCode": "KI",
    "iso3": "KIR",
    "phoneCode": "+686",
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "A$",
    "flag": "🇰🇮",
    "flagUrl": "https://flagcdn.com/w80/ki.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Kosovo",
    "isoCode": "XK",
    "iso3": "XKX",
    "phoneCode": "+377",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇽🇰",
    "flagUrl": "https://flagcdn.com/w80/xk.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Kuwait",
    "isoCode": "KW",
    "iso3": "KWT",
    "phoneCode": "+965",
    "currencyCode": "KWD",
    "currencyName": "Kuwaiti Dinar",
    "currencySymbol": "KD",
    "flag": "🇰🇼",
    "flagUrl": "https://flagcdn.com/w80/kw.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Kyrgyzstan",
    "isoCode": "KG",
    "iso3": "KGZ",
    "phoneCode": "+996",
    "currencyCode": "KGS",
    "currencyName": "KGS Currency",
    "currencySymbol": "KGS",
    "flag": "🇰🇬",
    "flagUrl": "https://flagcdn.com/w80/kg.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Laos",
    "isoCode": "LA",
    "iso3": "LAO",
    "phoneCode": "+856",
    "currencyCode": "LAK",
    "currencyName": "LAK Currency",
    "currencySymbol": "LAK",
    "flag": "🇱🇦",
    "flagUrl": "https://flagcdn.com/w80/la.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Latvia",
    "isoCode": "LV",
    "iso3": "LVA",
    "phoneCode": "+371",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇱🇻",
    "flagUrl": "https://flagcdn.com/w80/lv.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Lebanon",
    "isoCode": "LB",
    "iso3": "LBN",
    "phoneCode": "+961",
    "currencyCode": "LBP",
    "currencyName": "LBP Currency",
    "currencySymbol": "LBP",
    "flag": "🇱🇧",
    "flagUrl": "https://flagcdn.com/w80/lb.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Lesotho",
    "isoCode": "LS",
    "iso3": "LSO",
    "phoneCode": "+266",
    "currencyCode": "LSL",
    "currencyName": "LSL Currency",
    "currencySymbol": "LSL",
    "flag": "🇱🇸",
    "flagUrl": "https://flagcdn.com/w80/ls.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Liberia",
    "isoCode": "LR",
    "iso3": "LBR",
    "phoneCode": "+231",
    "currencyCode": "LRD",
    "currencyName": "LRD Currency",
    "currencySymbol": "LRD",
    "flag": "🇱🇷",
    "flagUrl": "https://flagcdn.com/w80/lr.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Libya",
    "isoCode": "LY",
    "iso3": "LBY",
    "phoneCode": "+218",
    "currencyCode": "LYD",
    "currencyName": "LYD Currency",
    "currencySymbol": "LYD",
    "flag": "🇱🇾",
    "flagUrl": "https://flagcdn.com/w80/ly.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Liechtenstein",
    "isoCode": "LI",
    "iso3": "LIE",
    "phoneCode": "+423",
    "currencyCode": "CHF",
    "currencyName": "Swiss Franc",
    "currencySymbol": "CHF",
    "flag": "🇱🇮",
    "flagUrl": "https://flagcdn.com/w80/li.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Lithuania",
    "isoCode": "LT",
    "iso3": "LTU",
    "phoneCode": "+370",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇱🇹",
    "flagUrl": "https://flagcdn.com/w80/lt.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Luxembourg",
    "isoCode": "LU",
    "iso3": "LUX",
    "phoneCode": "+352",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇱🇺",
    "flagUrl": "https://flagcdn.com/w80/lu.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Macao",
    "isoCode": "MO",
    "iso3": "MAC",
    "phoneCode": "+853",
    "currencyCode": "MOP",
    "currencyName": "MOP Currency",
    "currencySymbol": "MOP",
    "flag": "🇲🇴",
    "flagUrl": "https://flagcdn.com/w80/mo.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Madagascar",
    "isoCode": "MG",
    "iso3": "MDG",
    "phoneCode": "+261",
    "currencyCode": "MGA",
    "currencyName": "MGA Currency",
    "currencySymbol": "MGA",
    "flag": "🇲🇬",
    "flagUrl": "https://flagcdn.com/w80/mg.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Malawi",
    "isoCode": "MW",
    "iso3": "MWI",
    "phoneCode": "+265",
    "currencyCode": "MWK",
    "currencyName": "MWK Currency",
    "currencySymbol": "MWK",
    "flag": "🇲🇼",
    "flagUrl": "https://flagcdn.com/w80/mw.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Maldives",
    "isoCode": "MV",
    "iso3": "MDV",
    "phoneCode": "+960",
    "currencyCode": "MVR",
    "currencyName": "MVR Currency",
    "currencySymbol": "MVR",
    "flag": "🇲🇻",
    "flagUrl": "https://flagcdn.com/w80/mv.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Mali",
    "isoCode": "ML",
    "iso3": "MLI",
    "phoneCode": "+223",
    "currencyCode": "XOF",
    "currencyName": "XOF Currency",
    "currencySymbol": "XOF",
    "flag": "🇲🇱",
    "flagUrl": "https://flagcdn.com/w80/ml.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Marshall Islands",
    "isoCode": "MH",
    "iso3": "MHL",
    "phoneCode": "+692",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇲🇭",
    "flagUrl": "https://flagcdn.com/w80/mh.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Martinique",
    "isoCode": "MQ",
    "iso3": "MTQ",
    "phoneCode": "+596",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇲🇶",
    "flagUrl": "https://flagcdn.com/w80/mq.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Mauritania",
    "isoCode": "MR",
    "iso3": "MRT",
    "phoneCode": "+222",
    "currencyCode": "MRU",
    "currencyName": "MRU Currency",
    "currencySymbol": "MRU",
    "flag": "🇲🇷",
    "flagUrl": "https://flagcdn.com/w80/mr.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Mauritius",
    "isoCode": "MU",
    "iso3": "MUS",
    "phoneCode": "+230",
    "currencyCode": "MUR",
    "currencyName": "Mauritian Rupee",
    "currencySymbol": "Rs",
    "flag": "🇲🇺",
    "flagUrl": "https://flagcdn.com/w80/mu.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Mayotte",
    "isoCode": "YT",
    "iso3": "MYT",
    "phoneCode": "+262",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇾🇹",
    "flagUrl": "https://flagcdn.com/w80/yt.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Micronesia",
    "isoCode": "FM",
    "iso3": "FSM",
    "phoneCode": "+691",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇫🇲",
    "flagUrl": "https://flagcdn.com/w80/fm.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Moldova",
    "isoCode": "MD",
    "iso3": "MDA",
    "phoneCode": "+373",
    "currencyCode": "MDL",
    "currencyName": "MDL Currency",
    "currencySymbol": "MDL",
    "flag": "🇲🇩",
    "flagUrl": "https://flagcdn.com/w80/md.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Mongolia",
    "isoCode": "MN",
    "iso3": "MNG",
    "phoneCode": "+976",
    "currencyCode": "MNT",
    "currencyName": "MNT Currency",
    "currencySymbol": "MNT",
    "flag": "🇲🇳",
    "flagUrl": "https://flagcdn.com/w80/mn.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Montenegro",
    "isoCode": "ME",
    "iso3": "MNE",
    "phoneCode": "+382",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇲🇪",
    "flagUrl": "https://flagcdn.com/w80/me.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Montserrat",
    "isoCode": "MS",
    "iso3": "MSR",
    "phoneCode": "+1664",
    "currencyCode": "XCD",
    "currencyName": "XCD Currency",
    "currencySymbol": "XCD",
    "flag": "🇲🇸",
    "flagUrl": "https://flagcdn.com/w80/ms.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Morocco",
    "isoCode": "MA",
    "iso3": "MAR",
    "phoneCode": "+212",
    "currencyCode": "MAD",
    "currencyName": "Moroccan Dirham",
    "currencySymbol": "MAD",
    "flag": "🇲🇦",
    "flagUrl": "https://flagcdn.com/w80/ma.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Mozambique",
    "isoCode": "MZ",
    "iso3": "MOZ",
    "phoneCode": "+258",
    "currencyCode": "MZN",
    "currencyName": "MZN Currency",
    "currencySymbol": "MZN",
    "flag": "🇲🇿",
    "flagUrl": "https://flagcdn.com/w80/mz.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Myanmar",
    "isoCode": "MM",
    "iso3": "MMR",
    "phoneCode": "+95",
    "currencyCode": "MMK",
    "currencyName": "MMK Currency",
    "currencySymbol": "MMK",
    "flag": "🇲🇲",
    "flagUrl": "https://flagcdn.com/w80/mm.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Namibia",
    "isoCode": "NA",
    "iso3": "NAM",
    "phoneCode": "+264",
    "currencyCode": "NAD",
    "currencyName": "Namibian Dollar",
    "currencySymbol": "N$",
    "flag": "🇳🇦",
    "flagUrl": "https://flagcdn.com/w80/na.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Nauru",
    "isoCode": "NR",
    "iso3": "NRU",
    "phoneCode": "+674",
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "A$",
    "flag": "🇳🇷",
    "flagUrl": "https://flagcdn.com/w80/nr.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Nepal",
    "isoCode": "NP",
    "iso3": "NPL",
    "phoneCode": "+977",
    "currencyCode": "NPR",
    "currencyName": "Nepalese Rupee",
    "currencySymbol": "Rs",
    "flag": "🇳🇵",
    "flagUrl": "https://flagcdn.com/w80/np.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "New Caledonia",
    "isoCode": "NC",
    "iso3": "NCL",
    "phoneCode": "+687",
    "currencyCode": "XPF",
    "currencyName": "XPF Currency",
    "currencySymbol": "XPF",
    "flag": "🇳🇨",
    "flagUrl": "https://flagcdn.com/w80/nc.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Nicaragua",
    "isoCode": "NI",
    "iso3": "NIC",
    "phoneCode": "+505",
    "currencyCode": "NIO",
    "currencyName": "NIO Currency",
    "currencySymbol": "NIO",
    "flag": "🇳🇮",
    "flagUrl": "https://flagcdn.com/w80/ni.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Niger",
    "isoCode": "NE",
    "iso3": "NER",
    "phoneCode": "+227",
    "currencyCode": "XOF",
    "currencyName": "XOF Currency",
    "currencySymbol": "XOF",
    "flag": "🇳🇪",
    "flagUrl": "https://flagcdn.com/w80/ne.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Nigeria",
    "isoCode": "NG",
    "iso3": "NGA",
    "phoneCode": "+234",
    "currencyCode": "NGN",
    "currencyName": "Nigerian Naira",
    "currencySymbol": "₦",
    "flag": "🇳🇬",
    "flagUrl": "https://flagcdn.com/w80/ng.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Niue",
    "isoCode": "NU",
    "iso3": "NIU",
    "phoneCode": "+683",
    "currencyCode": "NZD",
    "currencyName": "New Zealand Dollar",
    "currencySymbol": "NZ$",
    "flag": "🇳🇺",
    "flagUrl": "https://flagcdn.com/w80/nu.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Norfolk Island",
    "isoCode": "NF",
    "iso3": "NFK",
    "phoneCode": "+672",
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "A$",
    "flag": "🇳🇫",
    "flagUrl": "https://flagcdn.com/w80/nf.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "North Korea",
    "isoCode": "KP",
    "iso3": "PRK",
    "phoneCode": "+850",
    "currencyCode": "KPW",
    "currencyName": "KPW Currency",
    "currencySymbol": "KPW",
    "flag": "🇰🇵",
    "flagUrl": "https://flagcdn.com/w80/kp.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "North Macedonia",
    "isoCode": "MK",
    "iso3": "MKD",
    "phoneCode": "+389",
    "currencyCode": "MKD",
    "currencyName": "MKD Currency",
    "currencySymbol": "MKD",
    "flag": "🇲🇰",
    "flagUrl": "https://flagcdn.com/w80/mk.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Northern Mariana Islands",
    "isoCode": "MP",
    "iso3": "MNP",
    "phoneCode": "+1670",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇲🇵",
    "flagUrl": "https://flagcdn.com/w80/mp.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Pakistan",
    "isoCode": "PK",
    "iso3": "PAK",
    "phoneCode": "+92",
    "currencyCode": "PKR",
    "currencyName": "Pakistani Rupee",
    "currencySymbol": "Rs",
    "flag": "🇵🇰",
    "flagUrl": "https://flagcdn.com/w80/pk.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Palau",
    "isoCode": "PW",
    "iso3": "PLW",
    "phoneCode": "+680",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇵🇼",
    "flagUrl": "https://flagcdn.com/w80/pw.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Palestine",
    "isoCode": "PS",
    "iso3": "PSE",
    "phoneCode": "+970",
    "currencyCode": "ILS",
    "currencyName": "Israeli Shekel",
    "currencySymbol": "₪",
    "flag": "🇵🇸",
    "flagUrl": "https://flagcdn.com/w80/ps.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Panama",
    "isoCode": "PA",
    "iso3": "PAN",
    "phoneCode": "+507",
    "currencyCode": "PAB",
    "currencyName": "PAB Currency",
    "currencySymbol": "PAB",
    "flag": "🇵🇦",
    "flagUrl": "https://flagcdn.com/w80/pa.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Papua New Guinea",
    "isoCode": "PG",
    "iso3": "PNG",
    "phoneCode": "+675",
    "currencyCode": "PGK",
    "currencyName": "PGK Currency",
    "currencySymbol": "PGK",
    "flag": "🇵🇬",
    "flagUrl": "https://flagcdn.com/w80/pg.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Paraguay",
    "isoCode": "PY",
    "iso3": "PRY",
    "phoneCode": "+595",
    "currencyCode": "PYG",
    "currencyName": "PYG Currency",
    "currencySymbol": "PYG",
    "flag": "🇵🇾",
    "flagUrl": "https://flagcdn.com/w80/py.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Peru",
    "isoCode": "PE",
    "iso3": "PER",
    "phoneCode": "+51",
    "currencyCode": "PEN",
    "currencyName": "Peruvian Sol",
    "currencySymbol": "S/",
    "flag": "🇵🇪",
    "flagUrl": "https://flagcdn.com/w80/pe.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Pitcairn Islands",
    "isoCode": "PN",
    "iso3": "PCN",
    "phoneCode": "+64",
    "currencyCode": "NZD",
    "currencyName": "New Zealand Dollar",
    "currencySymbol": "NZ$",
    "flag": "🇵🇳",
    "flagUrl": "https://flagcdn.com/w80/pn.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Poland",
    "isoCode": "PL",
    "iso3": "POL",
    "phoneCode": "+48",
    "currencyCode": "PLN",
    "currencyName": "Polish Zloty",
    "currencySymbol": "zł",
    "flag": "🇵🇱",
    "flagUrl": "https://flagcdn.com/w80/pl.png",
    "imageUrl": "https://images.unsplash.com/photo-1519197924294-4ba991a11128?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Puerto Rico",
    "isoCode": "PR",
    "iso3": "PRI",
    "phoneCode": "+1787",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇵🇷",
    "flagUrl": "https://flagcdn.com/w80/pr.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Republic of the Congo",
    "isoCode": "CG",
    "iso3": "COG",
    "phoneCode": "+242",
    "currencyCode": "XAF",
    "currencyName": "XAF Currency",
    "currencySymbol": "XAF",
    "flag": "🇨🇬",
    "flagUrl": "https://flagcdn.com/w80/cg.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Reunion",
    "isoCode": "RE",
    "iso3": "REU",
    "phoneCode": "+262",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇷🇪",
    "flagUrl": "https://flagcdn.com/w80/re.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Romania",
    "isoCode": "RO",
    "iso3": "ROU",
    "phoneCode": "+40",
    "currencyCode": "RON",
    "currencyName": "Romanian Leu",
    "currencySymbol": "lei",
    "flag": "🇷🇴",
    "flagUrl": "https://flagcdn.com/w80/ro.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Russia",
    "isoCode": "RU",
    "iso3": "RUS",
    "phoneCode": "+7",
    "currencyCode": "RUB",
    "currencyName": "Russian Ruble",
    "currencySymbol": "₽",
    "flag": "🇷🇺",
    "flagUrl": "https://flagcdn.com/w80/ru.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Rwanda",
    "isoCode": "RW",
    "iso3": "RWA",
    "phoneCode": "+250",
    "currencyCode": "RWF",
    "currencyName": "RWF Currency",
    "currencySymbol": "RWF",
    "flag": "🇷🇼",
    "flagUrl": "https://flagcdn.com/w80/rw.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Saint Barthelemy",
    "isoCode": "BL",
    "iso3": "BLM",
    "phoneCode": "+590",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇧🇱",
    "flagUrl": "https://flagcdn.com/w80/bl.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Saint Helena",
    "isoCode": "SH",
    "iso3": "SHN",
    "phoneCode": "+290",
    "currencyCode": "SHP",
    "currencyName": "SHP Currency",
    "currencySymbol": "SHP",
    "flag": "🇸🇭",
    "flagUrl": "https://flagcdn.com/w80/sh.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Saint Kitts and Nevis",
    "isoCode": "KN",
    "iso3": "KNA",
    "phoneCode": "+1869",
    "currencyCode": "XCD",
    "currencyName": "XCD Currency",
    "currencySymbol": "XCD",
    "flag": "🇰🇳",
    "flagUrl": "https://flagcdn.com/w80/kn.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Saint Lucia",
    "isoCode": "LC",
    "iso3": "LCA",
    "phoneCode": "+1758",
    "currencyCode": "XCD",
    "currencyName": "XCD Currency",
    "currencySymbol": "XCD",
    "flag": "🇱🇨",
    "flagUrl": "https://flagcdn.com/w80/lc.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Saint Martin",
    "isoCode": "MF",
    "iso3": "MAF",
    "phoneCode": "+590",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇲🇫",
    "flagUrl": "https://flagcdn.com/w80/mf.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Saint Pierre and Miquelon",
    "isoCode": "PM",
    "iso3": "SPM",
    "phoneCode": "+508",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇵🇲",
    "flagUrl": "https://flagcdn.com/w80/pm.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Saint Vincent and the Grenadines",
    "isoCode": "VC",
    "iso3": "VCT",
    "phoneCode": "+1784",
    "currencyCode": "XCD",
    "currencyName": "XCD Currency",
    "currencySymbol": "XCD",
    "flag": "🇻🇨",
    "flagUrl": "https://flagcdn.com/w80/vc.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Samoa",
    "isoCode": "WS",
    "iso3": "WSM",
    "phoneCode": "+685",
    "currencyCode": "WST",
    "currencyName": "WST Currency",
    "currencySymbol": "WST",
    "flag": "🇼🇸",
    "flagUrl": "https://flagcdn.com/w80/ws.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "San Marino",
    "isoCode": "SM",
    "iso3": "SMR",
    "phoneCode": "+378",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇸🇲",
    "flagUrl": "https://flagcdn.com/w80/sm.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Sao Tome and Principe",
    "isoCode": "ST",
    "iso3": "STP",
    "phoneCode": "+239",
    "currencyCode": "STN",
    "currencyName": "STN Currency",
    "currencySymbol": "STN",
    "flag": "🇸🇹",
    "flagUrl": "https://flagcdn.com/w80/st.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Senegal",
    "isoCode": "SN",
    "iso3": "SEN",
    "phoneCode": "+221",
    "currencyCode": "XOF",
    "currencyName": "XOF Currency",
    "currencySymbol": "XOF",
    "flag": "🇸🇳",
    "flagUrl": "https://flagcdn.com/w80/sn.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Serbia",
    "isoCode": "RS",
    "iso3": "SRB",
    "phoneCode": "+381",
    "currencyCode": "RSD",
    "currencyName": "Serbian Dinar",
    "currencySymbol": "din",
    "flag": "🇷🇸",
    "flagUrl": "https://flagcdn.com/w80/rs.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Seychelles",
    "isoCode": "SC",
    "iso3": "SYC",
    "phoneCode": "+248",
    "currencyCode": "SCR",
    "currencyName": "SCR Currency",
    "currencySymbol": "SCR",
    "flag": "🇸🇨",
    "flagUrl": "https://flagcdn.com/w80/sc.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Sierra Leone",
    "isoCode": "SL",
    "iso3": "SLE",
    "phoneCode": "+232",
    "currencyCode": "SLE",
    "currencyName": "SLE Currency",
    "currencySymbol": "SLE",
    "flag": "🇸🇱",
    "flagUrl": "https://flagcdn.com/w80/sl.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Sint Maarten",
    "isoCode": "SX",
    "iso3": "SXM",
    "phoneCode": "+1721",
    "currencyCode": "XCG",
    "currencyName": "XCG Currency",
    "currencySymbol": "XCG",
    "flag": "🇸🇽",
    "flagUrl": "https://flagcdn.com/w80/sx.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Slovakia",
    "isoCode": "SK",
    "iso3": "SVK",
    "phoneCode": "+421",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇸🇰",
    "flagUrl": "https://flagcdn.com/w80/sk.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Slovenia",
    "isoCode": "SI",
    "iso3": "SVN",
    "phoneCode": "+386",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇸🇮",
    "flagUrl": "https://flagcdn.com/w80/si.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Solomon Islands",
    "isoCode": "SB",
    "iso3": "SLB",
    "phoneCode": "+677",
    "currencyCode": "SBD",
    "currencyName": "SBD Currency",
    "currencySymbol": "SBD",
    "flag": "🇸🇧",
    "flagUrl": "https://flagcdn.com/w80/sb.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Somalia",
    "isoCode": "SO",
    "iso3": "SOM",
    "phoneCode": "+252",
    "currencyCode": "SOS",
    "currencyName": "SOS Currency",
    "currencySymbol": "SOS",
    "flag": "🇸🇴",
    "flagUrl": "https://flagcdn.com/w80/so.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "South Georgia and the South Sandwich Islands",
    "isoCode": "GS",
    "iso3": "SGS",
    "phoneCode": "+500",
    "currencyCode": "GBP",
    "currencyName": "British Pound",
    "currencySymbol": "£",
    "flag": "🇬🇸",
    "flagUrl": "https://flagcdn.com/w80/gs.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "South Sudan",
    "isoCode": "SS",
    "iso3": "SSD",
    "phoneCode": "+211",
    "currencyCode": "SSP",
    "currencyName": "SSP Currency",
    "currencySymbol": "SSP",
    "flag": "🇸🇸",
    "flagUrl": "https://flagcdn.com/w80/ss.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Sri Lanka",
    "isoCode": "LK",
    "iso3": "LKA",
    "phoneCode": "+94",
    "currencyCode": "LKR",
    "currencyName": "Sri Lankan Rupee",
    "currencySymbol": "Rs",
    "flag": "🇱🇰",
    "flagUrl": "https://flagcdn.com/w80/lk.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Sudan",
    "isoCode": "SD",
    "iso3": "SDN",
    "phoneCode": "+249",
    "currencyCode": "SDG",
    "currencyName": "SDG Currency",
    "currencySymbol": "SDG",
    "flag": "🇸🇩",
    "flagUrl": "https://flagcdn.com/w80/sd.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Suriname",
    "isoCode": "SR",
    "iso3": "SUR",
    "phoneCode": "+597",
    "currencyCode": "SRD",
    "currencyName": "SRD Currency",
    "currencySymbol": "SRD",
    "flag": "🇸🇷",
    "flagUrl": "https://flagcdn.com/w80/sr.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Svalbard and Jan Mayen",
    "isoCode": "SJ",
    "iso3": "SJM",
    "phoneCode": "+4779",
    "currencyCode": "NOK",
    "currencyName": "Norwegian Krone",
    "currencySymbol": "kr",
    "flag": "🇸🇯",
    "flagUrl": "https://flagcdn.com/w80/sj.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Syria",
    "isoCode": "SY",
    "iso3": "SYR",
    "phoneCode": "+963",
    "currencyCode": "SYP",
    "currencyName": "SYP Currency",
    "currencySymbol": "SYP",
    "flag": "🇸🇾",
    "flagUrl": "https://flagcdn.com/w80/sy.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Taiwan",
    "isoCode": "TW",
    "iso3": "TWN",
    "phoneCode": "+886",
    "currencyCode": "TWD",
    "currencyName": "New Taiwan Dollar",
    "currencySymbol": "NT$",
    "flag": "🇹🇼",
    "flagUrl": "https://flagcdn.com/w80/tw.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Tajikistan",
    "isoCode": "TJ",
    "iso3": "TJK",
    "phoneCode": "+992",
    "currencyCode": "TJS",
    "currencyName": "TJS Currency",
    "currencySymbol": "TJS",
    "flag": "🇹🇯",
    "flagUrl": "https://flagcdn.com/w80/tj.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Tanzania",
    "isoCode": "TZ",
    "iso3": "TZA",
    "phoneCode": "+255",
    "currencyCode": "TZS",
    "currencyName": "TZS Currency",
    "currencySymbol": "TZS",
    "flag": "🇹🇿",
    "flagUrl": "https://flagcdn.com/w80/tz.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Togo",
    "isoCode": "TG",
    "iso3": "TGO",
    "phoneCode": "+228",
    "currencyCode": "XOF",
    "currencyName": "XOF Currency",
    "currencySymbol": "XOF",
    "flag": "🇹🇬",
    "flagUrl": "https://flagcdn.com/w80/tg.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Tokelau",
    "isoCode": "TK",
    "iso3": "TKL",
    "phoneCode": "+690",
    "currencyCode": "NZD",
    "currencyName": "New Zealand Dollar",
    "currencySymbol": "NZ$",
    "flag": "🇹🇰",
    "flagUrl": "https://flagcdn.com/w80/tk.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Tonga",
    "isoCode": "TO",
    "iso3": "TON",
    "phoneCode": "+676",
    "currencyCode": "TOP",
    "currencyName": "TOP Currency",
    "currencySymbol": "TOP",
    "flag": "🇹🇴",
    "flagUrl": "https://flagcdn.com/w80/to.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Trinidad and Tobago",
    "isoCode": "TT",
    "iso3": "TTO",
    "phoneCode": "+1868",
    "currencyCode": "TTD",
    "currencyName": "Trinidad and Tobago Dollar",
    "currencySymbol": "TT$",
    "flag": "🇹🇹",
    "flagUrl": "https://flagcdn.com/w80/tt.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Tristan da Cunha",
    "isoCode": "TA",
    "iso3": "TAA",
    "phoneCode": "+290",
    "currencyCode": "SHP",
    "currencyName": "SHP Currency",
    "currencySymbol": "SHP",
    "flag": "🇹🇦",
    "flagUrl": "https://flagcdn.com/w80/ta.png",
    "imageUrl": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Tunisia",
    "isoCode": "TN",
    "iso3": "TUN",
    "phoneCode": "+216",
    "currencyCode": "TND",
    "currencyName": "Tunisian Dinar",
    "currencySymbol": "DT",
    "flag": "🇹🇳",
    "flagUrl": "https://flagcdn.com/w80/tn.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Turkmenistan",
    "isoCode": "TM",
    "iso3": "TKM",
    "phoneCode": "+993",
    "currencyCode": "TMT",
    "currencyName": "TMT Currency",
    "currencySymbol": "TMT",
    "flag": "🇹🇲",
    "flagUrl": "https://flagcdn.com/w80/tm.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Turks and Caicos Islands",
    "isoCode": "TC",
    "iso3": "TCA",
    "phoneCode": "+1649",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇹🇨",
    "flagUrl": "https://flagcdn.com/w80/tc.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Tuvalu",
    "isoCode": "TV",
    "iso3": "TUV",
    "phoneCode": "+688",
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "A$",
    "flag": "🇹🇻",
    "flagUrl": "https://flagcdn.com/w80/tv.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "U.S. Minor Outlying Islands",
    "isoCode": "UM",
    "iso3": "UMI",
    "phoneCode": "+1",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇺🇲",
    "flagUrl": "https://flagcdn.com/w80/um.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "U.S. Virgin Islands",
    "isoCode": "VI",
    "iso3": "VIR",
    "phoneCode": "+1340",
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "flag": "🇻🇮",
    "flagUrl": "https://flagcdn.com/w80/vi.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Uganda",
    "isoCode": "UG",
    "iso3": "UGA",
    "phoneCode": "+256",
    "currencyCode": "UGX",
    "currencyName": "UGX Currency",
    "currencySymbol": "UGX",
    "flag": "🇺🇬",
    "flagUrl": "https://flagcdn.com/w80/ug.png",
    "imageUrl": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Ukraine",
    "isoCode": "UA",
    "iso3": "UKR",
    "phoneCode": "+380",
    "currencyCode": "UAH",
    "currencyName": "Ukrainian Hryvnia",
    "currencySymbol": "₴",
    "flag": "🇺🇦",
    "flagUrl": "https://flagcdn.com/w80/ua.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Uruguay",
    "isoCode": "UY",
    "iso3": "URY",
    "phoneCode": "+598",
    "currencyCode": "UYU",
    "currencyName": "Uruguayan Peso",
    "currencySymbol": "$U",
    "flag": "🇺🇾",
    "flagUrl": "https://flagcdn.com/w80/uy.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Uzbekistan",
    "isoCode": "UZ",
    "iso3": "UZB",
    "phoneCode": "+998",
    "currencyCode": "UZS",
    "currencyName": "UZS Currency",
    "currencySymbol": "UZS",
    "flag": "🇺🇿",
    "flagUrl": "https://flagcdn.com/w80/uz.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Vanuatu",
    "isoCode": "VU",
    "iso3": "VUT",
    "phoneCode": "+678",
    "currencyCode": "VUV",
    "currencyName": "VUV Currency",
    "currencySymbol": "VUV",
    "flag": "🇻🇺",
    "flagUrl": "https://flagcdn.com/w80/vu.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Vatican City",
    "isoCode": "VA",
    "iso3": "VAT",
    "phoneCode": "+379",
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "flag": "🇻🇦",
    "flagUrl": "https://flagcdn.com/w80/va.png",
    "imageUrl": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Venezuela",
    "isoCode": "VE",
    "iso3": "VEN",
    "phoneCode": "+58",
    "currencyCode": "VES",
    "currencyName": "VES Currency",
    "currencySymbol": "VES",
    "flag": "🇻🇪",
    "flagUrl": "https://flagcdn.com/w80/ve.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Vietnam",
    "isoCode": "VN",
    "iso3": "VNM",
    "phoneCode": "+84",
    "currencyCode": "VND",
    "currencyName": "Vietnamese Dong",
    "currencySymbol": "₫",
    "flag": "🇻🇳",
    "flagUrl": "https://flagcdn.com/w80/vn.png",
    "imageUrl": "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Wallis and Futuna",
    "isoCode": "WF",
    "iso3": "WLF",
    "phoneCode": "+681",
    "currencyCode": "XPF",
    "currencyName": "XPF Currency",
    "currencySymbol": "XPF",
    "flag": "🇼🇫",
    "flagUrl": "https://flagcdn.com/w80/wf.png",
    "imageUrl": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Western Sahara",
    "isoCode": "EH",
    "iso3": "ESH",
    "phoneCode": "+212",
    "currencyCode": "MAD",
    "currencyName": "Moroccan Dirham",
    "currencySymbol": "MAD",
    "flag": "🇪🇭",
    "flagUrl": "https://flagcdn.com/w80/eh.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Yemen",
    "isoCode": "YE",
    "iso3": "YEM",
    "phoneCode": "+967",
    "currencyCode": "YER",
    "currencyName": "YER Currency",
    "currencySymbol": "YER",
    "flag": "🇾🇪",
    "flagUrl": "https://flagcdn.com/w80/ye.png",
    "imageUrl": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Zambia",
    "isoCode": "ZM",
    "iso3": "ZMB",
    "phoneCode": "+260",
    "currencyCode": "ZMW",
    "currencyName": "ZMW Currency",
    "currencySymbol": "ZMW",
    "flag": "🇿🇲",
    "flagUrl": "https://flagcdn.com/w80/zm.png",
    "imageUrl": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    "name": "Zimbabwe",
    "isoCode": "ZW",
    "iso3": "ZWE",
    "phoneCode": "+263",
    "currencyCode": "ZWG",
    "currencyName": "ZWG Currency",
    "currencySymbol": "ZWG",
    "flag": "🇿🇼",
    "flagUrl": "https://flagcdn.com/w80/zw.png",
    "imageUrl": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80"
  }
];

export const WORLD_CURRENCIES: WorldCurrency[] = [
  { code: 'EUR', name: 'Euro', symbol: '€', rateFromEUR: 1.0, rateFromUSD: 0.92 },
  { code: 'USD', name: 'US Dollar', symbol: '$', rateFromEUR: 1.09, rateFromUSD: 1.0 },
  { code: 'GBP', name: 'British Pound', symbol: '£', rateFromEUR: 0.86, rateFromUSD: 0.79 },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', rateFromEUR: 91.2, rateFromUSD: 83.6 },
  { code: 'AED', name: 'UAE Dirham', symbol: 'AED', rateFromEUR: 3.99, rateFromUSD: 3.67 },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', rateFromEUR: 1.49, rateFromUSD: 1.37 },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', rateFromEUR: 1.66, rateFromUSD: 1.52 },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', rateFromEUR: 0.97, rateFromUSD: 0.89 },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', rateFromEUR: 165.2, rateFromUSD: 151.8 },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', rateFromEUR: 7.85, rateFromUSD: 7.23 },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', rateFromEUR: 1.47, rateFromUSD: 1.35 },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', rateFromEUR: 4.08, rateFromUSD: 3.75 },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼', rateFromEUR: 3.96, rateFromUSD: 3.64 },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', rateFromEUR: 37.4, rateFromUSD: 34.3 },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', rateFromEUR: 5.85, rateFromUSD: 5.37 },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', rateFromEUR: 19.8, rateFromUSD: 18.2 },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', rateFromEUR: 11.45, rateFromUSD: 10.51 },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', rateFromEUR: 11.62, rateFromUSD: 10.67 },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', rateFromEUR: 7.46, rateFromUSD: 6.85 },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', rateFromEUR: 4.31, rateFromUSD: 3.96 },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', rateFromEUR: 39.8, rateFromUSD: 36.5 },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'Mex$', rateFromEUR: 21.5, rateFromUSD: 19.7 },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', rateFromEUR: 1.78, rateFromUSD: 1.63 },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', rateFromEUR: 8.51, rateFromUSD: 7.81 },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', rateFromEUR: 17250, rateFromUSD: 15830 },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', rateFromEUR: 5.12, rateFromUSD: 4.70 },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', rateFromEUR: 62.4, rateFromUSD: 57.3 },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', rateFromEUR: 27100, rateFromUSD: 24860 },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', rateFromEUR: 52.8, rateFromUSD: 48.5 },
];
